### ISSUE TITLE
Please do not upload the .joplin-blog.json file to github

### ISSUE THREAD

**Issue by rxliuli** [yakumo-saki/techblog#2]
This will cause you to expose the joplin token, which in turn will cause anyone who knows your token to write a website to visit or even modify your notes while you are browsing.

https://github.com/yakumo-saki/techblog/blob/7697a854130cd0b28d0f59d4ade8e2589401c44f/.joplin-blog.json#L6

I suggest you regenerate the token, add .joplin-blog.json to the ignore file, and delete it from git

**Comment by yakumo-saki** [comment]
oh... Its very big mistake. Thanks for notify! 

- [x] delete .joplin-blog.json
- [x] ignore .joplin-blog.json
- [x] regenerate token

**Comment by rxliuli** [comment]
In addition, I observed that the language you set is ja, but it is not currently supported. Maybe you can raise a PR.

https://github.com/yakumo-saki/techblog/blob/7697a854130cd0b28d0f59d4ade8e2589401c44f/.joplin-blog.json#L3

Specifically, add ja.json under the _apps/joplin-blog/src/i18n_ directory, I will access it later

https://github.com/rxliuli/joplin-utils/tree/master/apps/joplin-blog/src/i18n

**Comment by yakumo-saki** [comment]
Thanks for giving me information. and Thanks for creating joplin-blog!
